#ifndef CONFIG_H
#define CONFIG_H

// function usage toggles
#define USING_AFXMESSAGEBOX
// #define USING_CDIALOG_DOMODAL
#define USING_CHISTORY_KEEPNEW
#define USING_CHISTORY_KEEP
#define USING_CHISTORY_UNDO
#define USING_CMAPDOC_UPDATEALLVIEWS
#define USING_CMAPENTITY_CMAPENTITY
// #define USING_CMAPFACE_COPYFROM
#define USING_CMAPFACE_CREATEFACE
#define USING_CMAPFACE_GETORIENTATION
#define USING_CMAPFACE_INITIALIZETEXTUREAXES
#define USING_CMAPFACE_SETTEXTURE
// #define USING_CMAPSOLID_ADDPLANE
#define USING_CMAPSOLID_CMAPSOLID
// #define USING_CMAPSOLID_CLIPBYFACE
#define USING_CMAPSOLID_SPLIT
// #define USING_CMAPSOLID_CREATEFROMPLANES
#define USING_CRENDER_DRAWTEXT
#define USING_CSOLIDFACES_MAKEFACE
// #define USING_CSTRDLG_CSTRDLG
#define USING_CMAPCLASS_ENUMCHILDREN
#define USING_GETHISTORY
#define USING_GETMAINWND
#define USING_MSG
#define USING_CMAPDOC_SETMODIFIEDFLAG
#define USING_CMAPDOC_DELETEOBJECT
#define USING_VALVEALLOC
// #define USING_WCKEYVALUES_GETVALUE
#define USING_SCRIPTDATAPTR
#define USING_CSELECTION_SELECTOBJECTLIST

// hook toggles
#define USING_HOOK_AFXWNDPROC
#define USING_HOOK_CHISTORY_MARKUNDOPOSITION
#define USING_HOOK_CLIPPER3D_DRAWBRUSHEXTENTS
// #define USING_HOOK_CFACEEDITSHEET_CLICKFACE
#define USING_HOOK_ENABLEMENUITEM
#define USING_HOOK_SELECTION3D_RENDERTOOL2D
#define USING_HOOK_LOADMENUW
#define USING_HOOK_LOADACCELERATORSA
// #define USING_HOOK_RENDERUTILS_DRAWBOUNDSTEXT
// #define USING_HOOK_CSTATUSBAR_SETPANETEXT
// #define USING_HOOK_CWND_SETFOCUS
#define USING_HOOK_CMAPDOC_SETACTIVEMAPDOC

// offset toggles
#define USING_OFFSET_CMAINFRAME_FACEEDITSHEET
#define USING_OFFSET_CFACEEDITSHEET_FACES

#endif // CONFIG_H
